


run: run.cpp
	g++ -std=c++14 `root-config --cflags` run.cpp -o run `root-config --libs` -lTMVA -lTreePlayer

clean:
	rm run

#g++ -std=c++14 `root-config --cflags` tmva.cpp -o tmva `root-config --libs` -lTMVA -lTreePlayer