#!/bin/bash


if [ $# -ne 1 ]; then
    echo "One arguument required:"
    echo "*submit"
    echo "*check"
    echo "*clean"
    exit 1
fi


VIN=/pnfs/uboone/resilient/users/rmurrell/vertex_quality_input
OUTPUT=/pnfs/uboone/scratch/users/rmurrell/vertex_quality_output
jobnumber=`ls $VIN/permutations/permutations* | wc -l`
makeupdir=$VIN/makeup 

mail=""
workdir=`pwd`
gridfile=rungrid.sh
gridfilemu=rungrid_makeup.sh


if [ "$1" == "submit" ]; then
    
    if [ ! -d "$OUTPUT" ]; then
	mkdir $OUTPUT
    fi
    if test "$(ls -A "$OUTPUT")"; then
	echo "$OUTPUT not empty"
	exit 0
    fi

    jobsub_submit -G uboone --OS=SL6 --expected-lifetime='8h' --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC,OFFSITE -N $jobnumber ${mail} file://${workdir}/$gridfile ${file##*/}


elif [ "$1" == "check" ]; then

    if [ -d $makeupdir ]; then
	rm -rf $makeupdir
    fi
    mkdir $makeupdir

    good_files=0
    increment=0

    for i in `seq 0 $((jobnumber-1))`; do
	missing=false
	if [ ! -d $OUTPUT/$i ]; then
	    echo "Directory $i not found!"
	    missing=true
	elif [ ! -f $OUTPUT/$i/RunVertexQuality$i.root ]; then
	    echo "RunVertexQuality$i.root not found!"
	    missing=true
	fi
	if [ "$missing" == true ]; then
	    echo permutations_$i.root > $makeupdir/$increment.txt
	    ((increment++))
	else
	    ((good_files++))
	fi
    done 

    echo "Good files: $good_files / $jobnumber"
    

elif [ "$1" == "makeup" ]; then

    if [ ! -d $makeupdir ]; then
	echo "Run check"
	exit 1
    fi

    for file in `ls $makeupdir`; do
	pfile=$(head -1 $makeupdir/$file)
	pdir=${pfile##*_}
	pdir=${pdir%.*}
	echo $OUTPUT/$pdir
	if [ -d "$OUTPUT/$pdir" ]; then
	    rm -r $OUTPUT/$pdir
	fi
    done

    jobsub_submit -G uboone --OS=SL6 --expected-lifetime='24h' --memory='4000MB' --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC,OFFSITE -N `ls $makeupdir | wc -l` ${mail} file://${workdir}/$gridfilemu ${file##*/}
    

elif [ "$1" == "clean" ]; then

    echo rm -rf /pnfs/uboone/scratch/users/rmurrell/vertex_quality_output/
    rm -rf /pnfs/uboone/scratch/users/rmurrell/vertex_quality_output/*

else
 
    echo "Unknown input argument $1"
    exit 1


fi