#!/bin/bash

mail=""
workdir=`pwd`
gridfile=rungrid.sh

RES=/pnfs/uboone/resilient/users/rmurrell/vertex_quality_input
OUTPUT=/pnfs/uboone/scratch/users/rmurrell/vertex_quality_output
if [ ! -d "$OUTPUT" ]; then
    mkdir $OUTPUT
fi
if test "$(ls -A "$OUTPUT")"; then
    echo "$OUTPUT not empty"
    exit 0
fi

jobsub_submit -G uboone --OS=SL6 --expected-lifetime='8h' --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC,OFFSITE -N `ls $RES/permutations* | wc -l` ${mail} file://${workdir}/$gridfile ${file##*/}
